-   repositories:
        - haadcode/orbit
        - haadcode/orbit-core
        - haadcode/orbit-textui
        - haadcode/orbit-crypto
        - haadcode/orbit-db
        - haadcode/orbit-db-store
        - haadcode/orbit-db-kvstore
        - haadcode/orbit-db-eventstore
        - haadcode/orbit-db-feedstore
        - haadcode/orbit-db-counterstore
        - haadcode/orbit-db-pubsub
        - haadcode/crdts
        - haadcode/ipfs-post
        - haadcode/go-ipfs-log
        - haadcode/ipfs-log

    milestones:
    # Q4/2016
    -   title: Distribution Builds
        state: open
        description: |
            Provide downloadable builds for Orbit
        due_on: 2016-12-23

    -   title: Web version of Orbit
        state: open
        description: |
            Bring Orbit back to the browser with js-ipfs and release a web client.
        due_on: 2016-12-14

    -   title: Network Enhancing Bots
        state: open
        description: |
            Orbit network will have bots that enchance the performance and functionality of the chat network.
        due_on: 2016-11-30

    -   title: Product Design
        state: open
        description: |
            Product Design Document for Orbit
        due_on: 2016-11-16

    # Q3/2016    
    -   title: Improve documentation and developer experience
        state: open
        description: |
            Write better documentation, write more examples, cleanup and refactor code where needed.
        due_on: 2016-11-09
        previousTitles:
            - Improve Orbit's and orbit-db's documentation and developer experience
            - Improve Orbit's documentation and developer experience

    -   title: Fix Orbit
        state: closed
        description: |
            Fix all the things that got broken in the past couple of months and bring together a version that uses both IPFS go and JS implementations.
        due_on: 2016-08-13

    -   title: Integrate Orbit with uPort
        state: closed
        description: |
            Use uPort Identity for Orbit's users.
        due_on: 2016-09-17

    -   title: Orbit with IPFS Pubsub
        state: closed
        description: |
            Integrate with IPFS Pubsub (if available)
        due_on: 2016-09-29

    labels:
    -   name: bug
        color: d93f0b

    -   name: Backlog
        color: fbca04

    -   name: Blocked
        color: 5319e7

    -   name: 'Difficulty: Easy'
        color: fef2c0

    -   name: 'Difficulty: Medium'
        color: c5def5

    -   name: 'Difficulty: Hard'
        color: f9d0c4

    -   name: duplicate
        color: cccccc

    -   name: enhancement
        color: 84b6eb

    -   name: goal
        color: e99695

    -   name: help wanted
        color: 15A81A

    -   name: In Progress
        color: 006b75

    -   name: invalid
        color: e6e6e6

    -   name: question
        color: cc317c

    -   name: discussion
        color: cc317c

    -   name: refactor
        color: bfdadc

    -   name: wontfix
        color: ffffff
